// nuxt/components/viewer/Viewer.vue
<template>
  <div ref="Root" class="nodi-viewer" :style="{ width: width }">
    <Axis v-show="viewable" ref="Axis" @click="onViewDirection" />
    <ul v-show="uiItemsSize > 0" class="ui dark-theme-color no-select">
      <li class="toggle--open-close px-2 py-2 d-flex flex-items-center" @click.prevent.stop="openGUI = !openGUI">
        <i v-show="!openGUI" class="" v-html="svg.triangleOpen" />
        <i v-show="openGUI" class="" v-html="svg.triangleClose" />
        <span class="ml-2 pr-8 user-select-none" v-text="openGUI ? 'Close' : 'Open'" />
      </li>
      <li v-show="openGUI">
        <ul ref="GUIList" class="py-1" />
      </li>
    </ul>
    <ul v-show="viewable" class="information position-absolute p-3 no-select">
      <li>
        <ul class="">
          <li>
            <span class="text-mono f5 mr-1">X</span>
            <span class="text-mono f5" v-text="boundingBox.x" />
          </li>
          <li>
            <span class="text-mono f5 mr-1">Y</span>
            <span class="text-mono f5" v-text="boundingBox.y" />
          </li>
          <li>
            <span class="text-mono f5 mr-1">Z</span>
            <span class="text-mono f5" v-text="boundingBox.z" />
          </li>
        </ul>
      </li>
    </ul>
    <ul v-show="viewable" class="operators position-absolute p-3 no-select">
      <li v-show="hasFrep" class="rendering ml-2">
        <select v-model="operators.quality" class="form-select" title="frep rendering quality" @change="onRenderingQuality">
          <option v-for="(value, key) in qualities" :key="key" :value="value" v-text="key" />
        </select>
      </li>
      <li class="rendering ml-2">
        <select v-model="operators.rendering" class="form-select" title="switch rendering mode" @change="onRenderingMode">
          <option v-for="(opt, index) in renderings" :key="index" :value="index" v-text="opt" />
        </select>
      </li>
      <li class="ml-2">
        <a title="toggle grid" :class="{ active: !operators.grid }" @click.prevent.stop="toggleGrid" v-html="svg.squareGrid" />
      </li>
      <li class="ml-1">
        <a title="toggle bounding box" :class="{ active: !operators.boundingBox }" @click.prevent.stop="toggleBoundingBox" v-html="svg.threed" />
      </li>
      <li class="ml-2">
        <a title="reset viewer camera" class="fixed-indicator" @click.prevent.stop="resetViewerCamera" v-html="svg.pin" />
      </li>
      <li class="ml-2">
        <a title="toggle fullscreen" :class="{ active: !operators.fullscreen }" @click.prevent.stop="toggleFullscreen" v-html="svg.fullscreen" />
      </li>
    </ul>
  </div>
</template>

<script lang="ts">

import { Prop, Component, Vue } from 'nuxt-property-decorator';
import octicons from '@primer/octicons';
import { Vector3 } from 'three';
import { NodeBase, RenderingMode, FrepRenderingQuality, UINodeBase, IDisposable } from '@nodi/core';

import Axis from './Axis.vue';
import UIListItem from './UIListItem.vue';

import Viewer from '~/assets/scripts/viewer/Viewer';

let viewer: Viewer;

@Component({
  components: {
    Axis
  }
})
export default class ViewerComponent extends Vue {
  $refs!: {
    Root: HTMLDivElement;
    Axis: Axis;
    GUIList: HTMLUListElement;
  };

  svg = {
    squareGrid: octicons.grabber.toSVG({ width: 22 }),
    threed: octicons.package.toSVG({ width: 22 }),
    pin: octicons.pin.toSVG({ width: 22 }),
    fullscreen: octicons['screen-full'].toSVG({ width: 22 }),
    triangleOpen: octicons['triangle-right'].toSVG({ width: 18, height: 18 }),
    triangleClose: octicons['triangle-down'].toSVG({ width: 18, height: 18 })
  };

  viewable: boolean = true;
  boundingBox: Vector3 = new Vector3();
  hasFrep: boolean = false;
  operators = {
    quality: FrepRenderingQuality.Normal,
    rendering: RenderingMode.Standard,
    grid: true,
    boundingBox: false,
    fullscreen: false
  };

  qualities = FrepRenderingQuality;
  renderings = Object.values(RenderingMode).filter(k => typeof (k) === 'string');
  openGUI: boolean = false;
  uiItems: UIListItem[] = [];
  uiListeners: IDisposable[] = [];

  get uiItemsSize (): number {
    return this.uiItems.length;
  }

  @Prop({ type: String, required: true })
  width!: string;

  @Prop({ type: Boolean, required: false, default: false })
  editor!: boolean;

  mounted (): void {
    viewer = new Viewer(this.$refs.Root);
    viewer.onViewChanged.on((camera) => {
      this.$refs.Axis.update(camera);
    });
    viewer.onBoundingBoxChanged.on(({ size, box }) => {
      this.boundingBox.copy(size);
      this.$emit('boundingboxchanged', box);
    });
    viewer.onFrepChanged.on((hasFrep) => {
      this.hasFrep = hasFrep;
    });
    viewer.setRenderingMode(this.operators.rendering);
    viewer.setGrid(this.operators.grid);
    viewer.setBoundingBox(this.operators.boundingBox);
    this.$refs.Axis.update(viewer.camera);
  }

  destroy (): void {
    this.clear();
  }

  private clearListeners (): void {
    this.uiListeners.forEach(l => l.dispose());
    this.uiListeners = [];
  }

  clear () {
    this.clearListeners();
    this.uiItems.forEach((i) => {
      this.$refs.GUIList.removeChild(i.$el);
      i.$destroy();
    });
    this.uiItems = [];
  }

  update (nodes: NodeBase[]): void {
    viewer.update(nodes.filter(node => !(node instanceof UINodeBase)));
    // viewer.debouncedUpdate(nodes.filter(node => !(node instanceof UINodeBase)));

    this.clearListeners();
    const UIs: UINodeBase[] = nodes.filter(node => (node instanceof UINodeBase) && node.enabled && node.processed) as UINodeBase[];

    // eslint-disable-next-line prefer-const
    let prev = UIs.map(ui => ui.visible);
    this.uiListeners = UIs.map((ui, i) => {
      const f = ({ node }: { node: NodeBase }) => {
        if (prev[i] !== node.visible) {
          this.updateUI(UIs.filter(ui => ui.visible));
          prev[i] = node.visible;
        }
      };
      const listener = ui.onStateChanged.on(f);
      return listener;
    });
    this.updateUI(UIs.filter(ui => ui.visible));
  }

  private updateUI (UIs: UINodeBase[]): void {
    UIs.sort((a: UINodeBase, b: UINodeBase) => {
      const oa = a.getOrder();
      const ob = b.getOrder();
      if (oa < ob) { return -1; } else if (oa === ob) { return 0; }
      return 1;
    });

    // Remove unused gui
    this.uiItems.filter((i) => {
      return !UIs.some(n => n.uuid === i.getUUID());
    }).forEach((i) => {
      this.$refs.GUIList.removeChild(i.$el);
      i.$destroy();
      const index = this.uiItems.indexOf(i);
      if (index >= 0) {
        this.uiItems.splice(index, 1);
      }
    });

    const length = UIs.length;
    let hasDiffOrder = false;
    UIs.forEach((ui, order) => {
      hasDiffOrder = hasDiffOrder || (ui.getOrder() !== order);
      ui.setOrder(order);

      const found = this.uiItems.find(vue => vue.getUUID() === ui.uuid);
      if (found !== undefined) {
        found.length = length;
        found.order = order;
        return;
      }

      const div = document.createElement('div');
      div.style.width = '100%';
      div.classList.add('d-inline-flex');
      div.classList.add('flex-items-center');
      ui.setupGUIElement(div);
      const constructor = Vue.extend(UIListItem);
      const instance = new constructor({
        key: ui.uuid,
        propsData: {
          editor: this.editor,
          order,
          length
        }
      }) as UIListItem;
      instance.$mount();
      instance.setup(ui.uuid, div);
      console.log(instance);

      instance.$on('change', (newOrder: number) => {
        ui.setOrder(newOrder);
      });
      instance.$on('up', () => {
        const index = this.uiItems.indexOf(instance);
        this.uiItems.splice(index, 1);
        this.uiItems.splice(index - 1, 0, instance);
        this.sortUIItems(this.uiItems);
      });
      instance.$on('down', () => {
        const index = this.uiItems.indexOf(instance);
        this.uiItems.splice(index, 1);
        this.uiItems.splice(index + 1, 0, instance);
        this.sortUIItems(this.uiItems);
      });
      this.uiItems.push(instance);
      this.$refs.GUIList.appendChild(instance.$el);
    });

    if (hasDiffOrder) {
      this.sortUIItems(this.uiItems);
    }
  }

  private sortUIItems (items: UIListItem[]): void {
    items.forEach((item) => {
      if (item.$el.parentElement !== null) {
        this.$refs.GUIList.removeChild(item.$el);
      }
    });

    const length = items.length;
    items.forEach((item, order) => {
      const props = item.$props;
      props.length = length;
      props.order = order;
      this.$refs.GUIList.appendChild(item.$el);
    });
  }

  onRenderingQuality () {
    viewer.setRenderingQuality(this.operators.quality);
  }

  onRenderingMode () {
    viewer.setRenderingMode(this.operators.rendering);
  }

  toggleGrid () {
    this.operators.grid = !this.operators.grid;
    viewer.setGrid(this.operators.grid);
  }

  toggleBoundingBox () {
    this.operators.boundingBox = !this.operators.boundingBox;
    viewer.setBoundingBox(this.operators.boundingBox);
  }

  toggleFullscreen () {
    this.operators.fullscreen = viewer.toggleFullscreen();
  }

  resetViewerCamera () {
    viewer.resetCamera();
  }

  onViewDirection (direction: Vector3) {
    viewer.setCameraDirection(direction);
  }

  public capture (): Blob | undefined {
    return viewer.capture();
  }
}

</script>

<style lang="scss">

@import "@/assets/styles/viewer.scss";

</style>

// web/src/components/organisms/Viewer.tsx
import React, { useRef, useEffect, useState } from 'react';
import Axis from './Axis';
import Viewer from 'assets/scripts/viewer/Viewer';

const ViewerComponent = ({ width }: { width: number }, editor) => {
  const rootRef = useRef(null);
  const axisRef = useRef(null);
  const guiListRef = useRef(null);
  const [openGUI, setOpenGUI] = useState(false);
  const [boundingBox, setBoundingBox] = useState({ x: 0, y: 0, z: 0 });
  const [hasFrep, setHasFrep] = useState(false);
  const [operators, setOperators] = useState({
    quality: 'Normal',
    rendering: 'Standard',
    grid: true,
    boundingBox: false,
    fullscreen: false
  });
  const [uiItems, setUIItems] = useState([]);
  const [uiItemsSize, setUIItemsSize] = useState(0);

  const svg = {
    squareGrid: '<svg>...</svg>',
    threed: '<svg>...</svg>',
    pin: '<svg>...</svg>',
    fullscreen: '<svg>...</svg>',
    triangleOpen: '<svg>...</svg>',
    triangleClose: '<svg>...</svg>'
  };

  useEffect(() => {
    const viewer = new Viewer(rootRef.current!);
    viewer.onViewChanged.on((camera) => {
      axisRef.current!.update(camera);
    });
    viewer.onBoundingBoxChanged.on(({ size, box }) => {
      setBoundingBox(size);
      // emit boundingboxchanged event
    });
    viewer.onFrepChanged.on((hasFrep) => {
      setHasFrep(hasFrep);
    });
    viewer.setRenderingMode(operators.rendering);
    viewer.setGrid(operators.grid);
    viewer.setBoundingBox(operators.boundingBox);
    axisRef.current.update(viewer.camera);

    return () => {
      // cleanup code
    };
  }, []);

  const clear = () => {
    // clear code
  };

  const update = (nodes) => {
    // update code
  };

  const updateUI = (UIs) => {
    // updateUI code
  };

  const sortUIItems = (items) => {
    // sortUIItems code
  };

  const onRenderingQuality = () => {
    // onRenderingQuality code
  };

  const onRenderingMode = () => {
    // onRenderingMode code
  };

  const toggleGrid = () => {
    // toggleGrid code
  };

  const toggleBoundingBox = () => {
    // toggleBoundingBox code
  };

  const toggleFullscreen = () => {
    // toggleFullscreen code
  };

  const resetViewerCamera = () => {
    // resetViewerCamera code
  };

  const onViewDirection = (direction) => {
    // onViewDirection code
  };

  const capture = () => {
    // capture code
  };

  return (
    <div ref={rootRef} className="nodi-viewer" style={{ width }}>
      <Axis ref={axisRef} onClick={onViewDirection} />
      <ul className="ui dark-theme-color no-select" style={{ display: uiItemsSize > 0 ? 'block' : 'none' }}>
        <li className="toggle--open-close px-2 py-2 d-flex flex-items-center" onClick={() => setOpenGUI(!openGUI)}>
          <i style={{ display: !openGUI ? 'block' : 'none' }} dangerouslySetInnerHTML={{ __html: svg.triangleOpen }} />
          <i style={{ display: openGUI ? 'block' : 'none' }} dangerouslySetInnerHTML={{ __html: svg.triangleClose }} />
          <span className="ml-2 pr-8 user-select-none">{openGUI ? 'Close' : 'Open'}</span>
        </li>
        {openGUI && (
          <li>
            <ul ref={guiListRef} className="py-1" />
          </li>
        )}
      </ul>
      <ul className="information position-absolute p-3 no-select" style={{ display: viewable ? 'block' : 'none' }}>
        <li>
          <ul>
            <li>
              <span className="text-mono f5 mr-1">X</span>
              <span className="text-mono f5">{boundingBox.x}</span>
            </li>
            <li>
              <span className="text-mono f5 mr-1">Y</span>
              <span className="text-mono f5">{boundingBox.y}</span>
            </li>
            <li>
              <span className="text-mono f5 mr-1">Z</span>
              <span className="text-mono f5">{boundingBox.z}</span>
            </li>
          </ul>
        </li>
      </ul>
      <ul className="operators position-absolute p-3 no-select" style={{ display: viewable ? 'block' : 'none' }}>
        {hasFrep && (
          <li className="rendering ml-2">
            <select
              value={operators.quality}
              className="form-select"
              title="frep rendering quality"
              onChange={onRenderingQuality}
            >
              {/* options */}
            </select>
          </li>
        )}
        <li className="rendering ml-2">
          <select
            value={operators.rendering}
            className="form-select"
            title="switch rendering mode"
            onChange={onRenderingMode}
          >
            {/* options */}
          </select>
        </li>
        <li className="ml-2">
          <a
            title="toggle grid"
            className={operators.grid ? 'active' : ''}
            onClick={toggleGrid}
            dangerouslySetInnerHTML={{ __html: svg.squareGrid }}
          />
        </li>
        <li className="ml-1">
          <a
            title="toggle bounding box"
            className={operators.boundingBox ? 'active' : ''}
            onClick={toggleBoundingBox}
            dangerouslySetInnerHTML={{ __html: svg.threed }}
          />
        </li>
        <li className="ml-2">
          <a
            title="reset viewer camera"
            className="fixed-indicator"
            onClick={resetViewerCamera}
            dangerouslySetInnerHTML={{ __html: svg.pin }}
          />
        </li>
        <li className="ml-2">
          <a
            title="toggle fullscreen"
            className={operators.fullscreen ? 'active' : ''}
            onClick={toggleFullscreen}
            dangerouslySetInnerHTML={{ __html: svg.fullscreen }}
          />
        </li>
      </ul>
    </div>
  );
};

export default ViewerComponent;
